# -*- coding: utf-8 -*-
"""Complete_Mortgage_RAG_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWmbbyf9LsVG4gAh9YPPGpLA0kQoE0k-

# 🏠 Mortgage Document RAG Pipeline — Complete (All Phases)

| Phase | Steps | What |
|-------|-------|------|
| **1 — Foundations** | 1-4 | Hybrid OCR ingestion, basic chunking, embeddings + index, basic RAG pipeline |
| **2 — Mortgage-Specific** | 5-7 | Recursive/semantic chunking, rich metadata, page-level LLM classification |
| **3 — Better Retrieval** | 8-9 | Hybrid search (Vector + BM25 + RRF), query rewriting + decomposition |
| **4 — Post-Retrieval** | 10-11 | Cross-encoder reranking, context cleanup (dedup, filter, trim) |
| **5 — UI** | 12 | Gradio chat interface with upload, sources, confidence display |
| **6 — Evaluation** | 13-14 | RAGAS + manual evaluation, pipeline comparison |

---
## 📦 Install All Dependencies
"""

# ─── System Dependencies ───
!apt-get update && apt-get install -y tesseract-ocr poppler-utils > /dev/null 2>&1

# ─── Core Stack (from your working code) ───
!CMAKE_ARGS="-DGGML_CUDA=on" pip install -q llama-cpp-python
!pip install -q llama-index llama-index-llms-llama-cpp \
  llama-index-embeddings-huggingface llama-index-postprocessor-colbert-rerank \
  llama-index-retrievers-bm25 \
  pymupdf pdf2image pytesseract Pillow \
  sentence-transformers llama-index-readers-file

# ─── Phase 1: OCR + Image Preprocessing ───
!pip install -q paddlepaddle paddleocr opencv-python-headless

# ─── Phase 3: BM25 + NLP ───
!pip install -q rank-bm25 nltk scikit-learn

# ─── Phase 5: UI ───
!pip install -q gradio

# ─── Phase 6: Evaluation ───
!pip install -q ragas datasets

# ─── NLTK data ───
import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)

print("\n✅ All dependencies installed.")

"""## 🤖 Load All Models (runs once)"""

import os
import re
import warnings
import numpy as np
warnings.filterwarnings('ignore')

from llama_index.core import Settings, VectorStoreIndex, Document, get_response_synthesizer
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.core.schema import NodeWithScore, TextNode
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# ── Download Mistral-7B-Instruct GGUF ──
model_url = "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
model_path = "mistral-7b-instruct-v0.2.Q4_K_M.gguf"

if not os.path.exists(model_path):
    print("📥 Downloading Mistral-7B... (this takes a few minutes)")
    !wget -q {model_url} -O {model_path}

# ── LLM ──
print("🚀 Loading LLM...")
llm = LlamaCPP(
    model_path=model_path,
    temperature=0.1,
    max_new_tokens=512,
    context_window=4096,
    generate_kwargs={},
    model_kwargs={"n_gpu_layers": -1},
    verbose=False
)

# ── Embeddings ──
print("🚀 Loading Embeddings (BGE-small-en-v1.5)...")
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# ── Reranker ──
print("🚀 Loading Reranker...")
reranker = SentenceTransformerRerank(
    model="cross-encoder/ms-marco-MiniLM-L-6-v2", top_n=3
)

# ── Global Settings ──
Settings.llm = llm
Settings.embed_model = embed_model

# ── PaddleOCR ──
from paddleocr import PaddleOCR
paddle_ocr = PaddleOCR(use_angle_cls=True, lang='en', show_log=False)

# ── Semantic model (for Phase 2 merging + Phase 4 dedup) ──
from sentence_transformers import SentenceTransformer, CrossEncoder
semantic_model = SentenceTransformer('BAAI/bge-small-en-v1.5')
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2', max_length=512)

print("\n✅ All models loaded.")

"""---
# ═══════════════════════════════════════════════════════
# PHASE 1 — FOUNDATIONS
# ═══════════════════════════════════════════════════════

## Step 1: Document Ingestion (Hybrid OCR + Image Preprocessing)

Per page: PyMuPDF digital extraction → PaddleOCR (forms/tables) → Tesseract (fallback).
Image preprocessing: grayscale → rescale 1.5x → adaptive threshold → bilateral denoise.
"""

import fitz  # PyMuPDF
import pytesseract
import cv2
from PIL import Image
from pdf2image import convert_from_path

def preprocess_image(pil_image):
    """Preprocess scanned page: grayscale → rescale 1.5x → adaptive threshold → bilateral denoise."""
    img = np.array(pil_image)
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    else:
        gray = img
    h, w = gray.shape
    scaled = cv2.resize(gray, (int(w * 1.5), int(h * 1.5)), interpolation=cv2.INTER_CUBIC)
    thresh = cv2.adaptiveThreshold(scaled, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 15, 8)
    denoised = cv2.bilateralFilter(thresh, 9, 75, 75)
    return denoised

def ocr_with_paddle(image_array):
    """PaddleOCR — better for dense forms, tables, mixed layouts."""
    try:
        results = paddle_ocr.ocr(image_array, cls=True)
        if not results or not results[0]:
            return ""
        return " ".join([line[1][0] for line in results[0] if line[1][1] > 0.5])
    except Exception as e:
        print(f"  ⚠️ PaddleOCR error: {e}")
        return ""

def ocr_with_tesseract(image_array):
    """Tesseract fallback — reliable for clean typed pages."""
    try:
        return pytesseract.image_to_string(Image.fromarray(image_array)).strip()
    except Exception as e:
        print(f"  ⚠️ Tesseract error: {e}")
        return ""

MIN_TEXT_LENGTH = 50

def ingest_pdf(pdf_path):
    """Ingest a single PDF. Returns list of page dicts."""
    filename = os.path.basename(pdf_path)
    doc = fitz.open(pdf_path)
    pages_data = []

    digital_texts = [page.get_text().strip() for page in doc]
    needs_ocr = any(len(t) < MIN_TEXT_LENGTH for t in digital_texts)
    page_images = convert_from_path(pdf_path, dpi=200) if needs_ocr else None

    if needs_ocr:
        print(f"  📷 Some pages need OCR — converting {filename} to images...")

    for i, page in enumerate(doc):
        text = digital_texts[i]
        source_type = "digital"

        if len(text) < MIN_TEXT_LENGTH and page_images:
            print(f"  🔍 OCR on page {i+1} of {filename}")
            preprocessed = preprocess_image(page_images[i])
            text = ocr_with_paddle(preprocessed)
            source_type = "ocr_paddle"
            if len(text) < MIN_TEXT_LENGTH:
                print(f"    ↪ PaddleOCR insufficient, trying Tesseract...")
                text = ocr_with_tesseract(preprocessed)
                source_type = "ocr_tesseract"

        pages_data.append({
            "filename": filename, "page_number": i + 1,
            "text": text, "source_type": source_type, "doc_type": "unknown"
        })

    doc.close()
    print(f"  ✅ {filename}: {len(pages_data)} pages ingested.")
    return pages_data

def ingest_all_pdfs(pdf_folder):
    """Ingest all PDFs from a folder."""
    all_pages = []
    pdf_files = sorted([f for f in os.listdir(pdf_folder) if f.lower().endswith('.pdf')])
    if not pdf_files:
        print(f"⚠️ No PDF files found in {pdf_folder}")
        return all_pages
    print(f"📂 Found {len(pdf_files)} PDF(s)\n")
    for fname in pdf_files:
        print(f"📄 Processing: {fname}")
        all_pages.extend(ingest_pdf(os.path.join(pdf_folder, fname)))
    print(f"\n🎯 Total pages ingested: {len(all_pages)}")
    return all_pages

print("✅ Step 1: Ingestion pipeline ready.")

"""## 📁 Upload PDFs & Run Ingestion"""

from google.colab import files

PDF_FOLDER = "/content/mortgage_docs"
os.makedirs(PDF_FOLDER, exist_ok=True)

print("Upload your mortgage PDF(s):")
uploaded = files.upload()
for fname, data in uploaded.items():
    with open(os.path.join(PDF_FOLDER, fname), 'wb') as f:
        f.write(data)
    print(f"  Saved: {fname}")

all_pages = ingest_all_pdfs(PDF_FOLDER)

for p in all_pages[:3]:
    print(f"\n{'='*60}")
    print(f"📄 {p['filename']} | Page {p['page_number']} | Source: {p['source_type']}")
    print(f"Text preview: {p['text'][:300]}...")

"""## Steps 2-3: Chunking + Embeddings + Vector Index (Phase 1 Baseline)"""

def create_documents_from_pages(pages):
    """Convert raw page dicts into LlamaIndex Documents."""
    documents = []
    for page in pages:
        if not page["text"].strip(): continue
        metadata = {
            "filename": page["filename"], "page_number": page["page_number"],
            "source_type": page["source_type"], "doc_type": page["doc_type"]
        }
        documents.append(Document(text=page["text"], metadata=metadata))
    print(f"📄 Created {len(documents)} LlamaIndex Documents.")
    return documents

all_documents = create_documents_from_pages(all_pages)
Settings.text_splitter = SentenceSplitter(chunk_size=512, chunk_overlap=50)

print("🔢 Building Phase 1 vector index...")
vector_index = VectorStoreIndex.from_documents(all_documents)
print("✅ Steps 2-3 complete: Phase 1 index built.")

"""## Step 4: Basic RAG Pipeline (`ask()`)"""

def ask(query, index=None, top_k=10, rerank_top_n=3):
    """
    Phase 1 RAG: Vector search → Rerank → LLM → Answer + sources.
    """
    if index is None:
        index = vector_index

    retriever = VectorIndexRetriever(index=index, similarity_top_k=top_k)
    reranker_inst = SentenceTransformerRerank(
        model="cross-encoder/ms-marco-MiniLM-L-6-v2", top_n=rerank_top_n
    )
    query_engine = RetrieverQueryEngine(
        retriever=retriever,
        response_synthesizer=get_response_synthesizer(response_mode="compact"),
        node_postprocessors=[reranker_inst]
    )
    response = query_engine.query(query)

    sources, scores = [], []
    for node in response.source_nodes:
        score = node.score if node.score else 0.0
        sources.append({
            "filename": node.metadata.get("filename", "?"),
            "page_number": node.metadata.get("page_number", "?"),
            "doc_type": node.metadata.get("doc_type", "unknown"),
            "score": round(score, 4),
            "preview": " ".join(node.get_text().split()[:25]) + "..."
        })
        scores.append(score)

    return {
        "answer": str(response),
        "sources": sources,
        "num_chunks_used": len(sources),
        "confidence": round(float(np.mean(scores)), 4) if scores else 0.0
    }

print("✅ Step 4: Basic RAG pipeline (ask) ready.")

# ── Quick Phase 1 Test ──
result = ask("What is the interest rate on the mortgage?")
print(f"💬 {result['answer'][:300]}")
print(f"📊 Confidence: {result['confidence']} | Chunks: {result['num_chunks_used']}")

"""---
# ═══════════════════════════════════════════════════════
# PHASE 2 — MORTGAGE-SPECIFIC UPGRADES
# ═══════════════════════════════════════════════════════

## Step 5: Smart Chunking (Recursive/Hierarchical + Semantic Merge)
"""

from sklearn.metrics.pairwise import cosine_similarity

# ─── Mortgage section header patterns ───
SECTION_PATTERNS = [
    r'(?:^|\n)(?:SECTION|Section|ARTICLE|Article)\s+\d+[.:]?\s+[A-Z]',
    r'(?:^|\n)\d{1,2}\.\s+[A-Z][A-Za-z]',
    r'(?:^|\n)([A-Z][A-Z\s]{5,})(?:\n|$)',
    r'(?:^|\n)\([a-z]\)\s',
    r'(?:^|\n)\([ivx]+\)\s',
]

def find_section_breaks(text):
    breaks = []
    for pattern in SECTION_PATTERNS:
        for match in re.finditer(pattern, text):
            breaks.append((match.start(), match.group().strip()))
    breaks.sort(key=lambda x: x[0])
    return breaks

def recursive_chunk(text, max_tokens=512, min_tokens=50):
    """Split by section headers → paragraphs → sentences."""
    breaks = find_section_breaks(text)
    if breaks:
        sections = []
        if breaks[0][0] > 0:
            preamble = text[:breaks[0][0]].strip()
            if len(preamble) > min_tokens:
                sections.append((preamble, "Preamble"))
        for i, (pos, header) in enumerate(breaks):
            end = breaks[i + 1][0] if i + 1 < len(breaks) else len(text)
            section_text = text[pos:end].strip()
            if section_text:
                sections.append((section_text, header))
    else:
        sections = [(text, "Full Page")]

    chunks = []
    for section_text, section_title in sections:
        if len(section_text.split()) * 1.3 <= max_tokens:
            chunks.append((section_text, section_title))
        else:
            paragraphs = re.split(r'\n\s*\n', section_text)
            current_chunk = ""
            for para in paragraphs:
                para = para.strip()
                if not para: continue
                test_chunk = current_chunk + "\n\n" + para if current_chunk else para
                if len(test_chunk.split()) * 1.3 <= max_tokens:
                    current_chunk = test_chunk
                else:
                    if current_chunk: chunks.append((current_chunk, section_title))
                    current_chunk = para
            if current_chunk: chunks.append((current_chunk, section_title))

    return [(t, s) for t, s in chunks if len(t.split()) >= 10]

def semantic_merge(chunks_with_titles, threshold=0.75, max_tokens=600):
    """Merge adjacent chunks if semantically similar."""
    if len(chunks_with_titles) <= 1: return chunks_with_titles
    texts = [c[0] for c in chunks_with_titles]
    embeddings = semantic_model.encode(texts, normalize_embeddings=True)
    merged = [chunks_with_titles[0]]
    for i in range(1, len(chunks_with_titles)):
        prev_text, prev_title = merged[-1]
        curr_text, curr_title = chunks_with_titles[i]
        sim = cosine_similarity(embeddings[i-1].reshape(1,-1), embeddings[i].reshape(1,-1))[0][0]
        combined = prev_text + "\n\n" + curr_text
        if sim >= threshold and len(combined.split()) * 1.3 <= max_tokens:
            merged[-1] = (combined, prev_title)
        else:
            merged.append((curr_text, curr_title))
    return merged

def smart_chunk_page(page_text, max_tokens=512, merge_threshold=0.75):
    """Recursive split → semantic merge."""
    raw = recursive_chunk(page_text, max_tokens=max_tokens)
    return semantic_merge(raw, threshold=merge_threshold)

print("✅ Step 5: Smart chunking ready.")

"""## Step 6: Rich Metadata + Step 7: Page-Level Classification"""

def detect_table_content(text):
    """Heuristic: does this chunk contain tabular data?"""
    indicators = 0
    if len(re.findall(r'^.*\d+[.,]\d+.*\d+[.,]\d+.*$', text, re.MULTILINE)) >= 3: indicators += 1
    if len(re.findall(r'^.+\s{3,}.+$', text, re.MULTILINE)) >= 3: indicators += 1
    if '|' in text or '\t' in text: indicators += 1
    if len(re.findall(r'\$[\d,]+', text)) >= 3: indicators += 1
    return indicators >= 2

def classify_doc_type_heuristic(text):
    """Quick keyword-based classification."""
    lower = text.lower()
    patterns = [
        ("closing disclosure", "Closing Disclosure"), ("loan estimate", "Loan Estimate"),
        ("promissory note", "Promissory Note"), ("deed of trust", "Deed of Trust"),
        ("mortgage agreement", "Mortgage Agreement"), ("loan agreement", "Loan Agreement"),
        ("appraisal", "Appraisal"), ("title insurance", "Title Insurance"),
        ("homeowners insurance", "Homeowners Insurance"),
        ("pay stub", "Pay Stub"), ("paystub", "Pay Stub"),
        ("bank statement", "Bank Statement"),
        ("w-2", "Tax Document (W-2)"), ("1099", "Tax Document (1099)"),
        ("tax return", "Tax Return"), ("escrow", "Escrow Statement"),
        ("agreement", "Contract/Agreement"), ("contract", "Contract/Agreement"),
        ("disclosure", "Disclosure"),
    ]
    for keyword, label in patterns:
        if keyword in lower: return label
    return "Unknown"

def classify_page_with_llm(page_text, llm):
    """LLM classifies a page into a mortgage document type."""
    snippet = page_text[:500].strip()
    if len(snippet) < 20: return "Unknown"
    prompt = f"""Classify this document page into ONE category:
- Loan Agreement
- Closing Disclosure
- Promissory Note
- Deed of Trust
- Loan Estimate
- Appraisal
- Title Insurance
- Homeowners Insurance
- Pay Stub
- Bank Statement
- Tax Document
- Escrow Statement
- Cover Letter / Correspondence
- Other

Respond with ONLY the category name.

Page content:
\"\"\"
{snippet}
\"\"\"

Category:"""
    try:
        response = llm.complete(prompt)
        label = str(response).strip().split('\n')[0].strip().strip('"\'.').strip()
        return label if len(label) < 50 else "Other"
    except: return "Unknown"

def classify_all_pages(pages, llm, use_llm=True):
    """Classify every page: heuristic first, LLM fallback."""
    print("🏷️  Classifying pages...")
    for page in pages:
        label = classify_doc_type_heuristic(page["text"])
        if label == "Unknown" and use_llm and len(page["text"].strip()) > 20:
            label = classify_page_with_llm(page["text"], llm)
            print(f"  Page {page['page_number']} ({page['filename']}): {label} [LLM]")
        else:
            print(f"  Page {page['page_number']} ({page['filename']}): {label} [heuristic]")
        page["doc_type"] = label
    print("✅ Classification complete.")
    return pages

print("✅ Steps 6-7: Metadata + classification ready.")

"""## Run Phase 2: Classify → Smart Chunk → Rebuild Index"""

# Classify all pages
all_pages = classify_all_pages(all_pages, llm, use_llm=True)

from collections import Counter
type_counts = Counter(p["doc_type"] for p in all_pages)
print("\n📊 Document Type Distribution:")
for doc_type, count in type_counts.most_common():
    print(f"  {doc_type}: {count} page(s)")

def build_phase2_documents(pages):
    """Smart chunking + rich metadata → LlamaIndex Documents."""
    documents = []
    chunk_count = 0
    for page in pages:
        if not page["text"].strip(): continue
        chunks = smart_chunk_page(page["text"], max_tokens=512, merge_threshold=0.75)
        for chunk_text, section_title in chunks:
            metadata = {
                "filename": page["filename"], "page_number": page["page_number"],
                "doc_type": page["doc_type"], "source_type": page["source_type"],
                "section_title": section_title,
                "table_present": detect_table_content(chunk_text),
                "chunk_id": chunk_count
            }
            documents.append(Document(text=chunk_text, metadata=metadata))
            chunk_count += 1
    print(f"📦 Phase 2: {len(documents)} smart chunks created.")
    return documents

phase2_documents = build_phase2_documents(all_pages)

# Rebuild index (bypass LlamaIndex re-splitting)
Settings.text_splitter = SentenceSplitter(chunk_size=2048, chunk_overlap=0)
print("🔢 Building Phase 2 vector index...")
vector_index_v2 = VectorStoreIndex.from_documents(phase2_documents)
print("✅ Phase 2 index built.")

"""---
# ═══════════════════════════════════════════════════════
# PHASE 3 — BETTER RETRIEVAL
# ═══════════════════════════════════════════════════════

## Step 8: Hybrid Retrieval (Vector + BM25 + RRF)
"""

from rank_bm25 import BM25Okapi
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

STOP_WORDS = set(stopwords.words('english'))

def tokenize_for_bm25(text):
    text = text.lower()
    tokens = word_tokenize(text)
    return [t for t in tokens if (t.isalnum() or '$' in t or '%' in t) and t not in STOP_WORDS]

class BM25Index:
    def __init__(self, documents):
        self.documents = documents
        self.corpus_tokens = [tokenize_for_bm25(doc.text) for doc in documents]
        self.bm25 = BM25Okapi(self.corpus_tokens)
        print(f"  ✅ BM25 index: {len(documents)} documents.")

    def search(self, query, top_k=10):
        scores = self.bm25.get_scores(tokenize_for_bm25(query))
        top_indices = np.argsort(scores)[::-1][:top_k]
        return [(self.documents[i], float(scores[i])) for i in top_indices if scores[i] > 0]

# Always build manual BM25 as a guaranteed fallback
bm25_index = BM25Index(phase2_documents)

# Try LlamaIndex-native BM25 as preferred option
USE_LLAMAINDEX_BM25 = False
llamaindex_bm25 = None
try:
    from llama_index.retrievers.bm25 import BM25Retriever
    llamaindex_bm25 = BM25Retriever.from_defaults(
        docstore=vector_index_v2.docstore, similarity_top_k=10
    )
    USE_LLAMAINDEX_BM25 = True
    print("✅ Using LlamaIndex BM25Retriever (preferred).")
except Exception as e:
    print(f"⚠️ LlamaIndex BM25 unavailable ({e}), using manual BM25.")


def vector_search(query, index, top_k=10):
    """Vector search wrapper returning (Document, score) tuples."""
    nodes = VectorIndexRetriever(index=index, similarity_top_k=top_k).retrieve(query)
    return [(Document(text=n.get_text(), metadata=n.metadata), n.score or 0.0) for n in nodes]


def reciprocal_rank_fusion(result_lists, k=60):
    """Merge ranked lists with RRF. Returns [(doc, rrf_score)]."""
    doc_scores, doc_objects = {}, {}
    for result_list in result_lists:
        for rank, (doc, _) in enumerate(result_list):
            key = doc.text[:200].strip()
            if key not in doc_scores:
                doc_scores[key] = 0.0
                doc_objects[key] = doc
            doc_scores[key] += 1.0 / (k + rank + 1)
    sorted_keys = sorted(doc_scores, key=lambda x: doc_scores[x], reverse=True)
    return [(doc_objects[k], doc_scores[k]) for k in sorted_keys]


def hybrid_retrieve(query, vector_idx, top_k=10):
    """Hybrid: Vector + BM25 → RRF fusion."""
    vector_results = vector_search(query, vector_idx, top_k=top_k)

    if USE_LLAMAINDEX_BM25:
        bm25_nodes = llamaindex_bm25.retrieve(query)
        bm25_results = [(Document(text=n.get_text(), metadata=n.metadata), n.score or 0.0) for n in bm25_nodes]
    else:
        bm25_results = bm25_index.search(query, top_k=top_k)

    fused = reciprocal_rank_fusion([vector_results, bm25_results], k=60)
    return fused[:top_k]


print("✅ Step 8: Hybrid retrieval ready.")

"""## Step 9: Query Processing (Rewriting + Decomposition)"""

def rewrite_query(user_query, llm):
    """LLM rewrites vague question into precise mortgage-specific retrieval query."""
    prompt = f"""You are a query rewriting assistant for a mortgage document search system.
Rewrite the user's question to be more specific and comprehensive for searching mortgage documents.
Add relevant mortgage/legal terminology. Keep it as a single search query.

User question: "{user_query}"

Rewritten query:"""
    try:
        response = llm.complete(prompt)
        rewritten = str(response).strip().split('\n')[0].strip().strip('"\'')
        return rewritten if 5 <= len(rewritten) <= 500 else user_query
    except:
        return user_query


def decompose_query(user_query, llm):
    """Break complex questions into 2-4 focused sub-queries."""
    prompt = f"""You are a query decomposition assistant for a mortgage document search system.
If the question is simple, return just the original question.
If complex, break into 2-4 focused sub-questions.
Return ONLY the sub-questions, one per line. No numbering, no bullets.

Question: "{user_query}"

Sub-questions:"""
    try:
        response = llm.complete(prompt)
        sub_queries = []
        for line in str(response).strip().split('\n'):
            line = line.strip().strip('-•*0123456789.)').strip().strip('"\'')
            if len(line) > 10: sub_queries.append(line)
        return sub_queries[:4] if sub_queries else [user_query]
    except:
        return [user_query]


print("✅ Step 9: Query processing ready.")

"""---
# ═══════════════════════════════════════════════════════
# PHASE 4 — POST-RETRIEVAL OPTIMIZATION
# ═══════════════════════════════════════════════════════

## Step 10: Reranking + Step 11: Context Cleanup
"""

from sklearn.metrics.pairwise import cosine_similarity as cos_sim

def rerank_results(query, results, top_n=5):
    """Cross-encoder reranking."""
    if not results: return []
    pairs = [(query, doc.text[:512]) for doc, _ in results]
    ce_scores = cross_encoder.predict(pairs)
    scored = list(zip([doc for doc, _ in results], ce_scores))
    scored.sort(key=lambda x: x[1], reverse=True)
    return scored[:top_n]


def clean_context(reranked, min_score=-5.0, dedup_threshold=0.92, max_context_tokens=2000):
    """Filter by score, remove near-duplicates, enforce token budget."""
    if not reranked: return []

    # Score filter
    filtered = [(d, s) for d, s in reranked if s >= min_score]
    if not filtered: filtered = [reranked[0]]

    # Dedup
    if len(filtered) > 1:
        texts = [d.text for d, _ in filtered]
        embs = semantic_model.encode(texts, normalize_embeddings=True)
        keep = [0]
        for i in range(1, len(filtered)):
            if all(cos_sim(embs[i].reshape(1,-1), embs[j].reshape(1,-1))[0][0] < dedup_threshold for j in keep):
                keep.append(i)
        filtered = [filtered[i] for i in keep]

    # Token budget
    final, total = [], 0
    for doc, score in filtered:
        tokens = len(doc.text.split()) * 1.3
        if total + tokens <= max_context_tokens:
            final.append((doc, score))
            total += tokens
        else: break
    return final


print("✅ Steps 10-11: Reranking + context cleanup ready.")

"""## Full Pipeline: `ask_v3()` (All Phases Combined)"""

def ask_v3(
    query,
    vector_idx=None,
    use_rewrite=True,
    use_decomposition=True,
    hybrid_top_k=10,
    rerank_top_n=5,
    max_context_tokens=2000,
    verbose=True
):
    """
    Complete RAG pipeline:
    Rewrite → Decompose → Hybrid Retrieve → Rerank → Cleanup → LLM Answer.
    """
    if vector_idx is None: vector_idx = vector_index_v2
    debug = {"original_query": query}

    # 1. Query Rewriting
    rewritten = rewrite_query(query, llm) if use_rewrite else query
    debug["rewritten_query"] = rewritten
    if verbose: print(f"  ✏️  Rewritten: {rewritten}")

    # 2. Query Decomposition
    sub_queries = decompose_query(rewritten, llm) if use_decomposition else [rewritten]
    debug["sub_queries"] = sub_queries
    if verbose: print(f"  🔀 Sub-queries: {sub_queries}")

    # 3. Hybrid Retrieval per sub-query
    all_retrieved = []
    for sq in sub_queries:
        results = hybrid_retrieve(sq, vector_idx, top_k=hybrid_top_k)
        all_retrieved.extend(results)
        if verbose: print(f"  🔍 '{sq[:50]}...' → {len(results)} results")

    # Dedup across sub-queries
    seen = set()
    unique = []
    for doc, score in all_retrieved:
        key = doc.text[:200].strip()
        if key not in seen:
            seen.add(key)
            unique.append((doc, score))

    if verbose: print(f"  📦 Unique results: {len(unique)}")
    if not unique:
        return {"answer": "No relevant documents found.", "sources": [],
                "num_chunks_used": 0, "confidence": 0.0, "debug": debug}

    # 4. Cross-Encoder Reranking
    reranked = rerank_results(query, unique, top_n=rerank_top_n)
    if verbose: print(f"  🏆 Reranked: {len(reranked)}")

    # 5. Context Cleanup
    cleaned = clean_context(reranked, max_context_tokens=max_context_tokens)
    if verbose: print(f"  🧹 After cleanup: {len(cleaned)}")

    # 6. Build prompt + generate
    context_parts = []
    for i, (doc, score) in enumerate(cleaned):
        m = doc.metadata
        context_parts.append(
            f"[Source {i+1}: {m.get('filename','?')}, Page {m.get('page_number','?')}, "
            f"Type: {m.get('doc_type','?')}, Section: {m.get('section_title','?')}]\n{doc.text}"
        )

    context_block = "\n\n---\n\n".join(context_parts)

    prompt = f"""You are a mortgage document analysis assistant. Answer ONLY from the provided context.
If the answer is not in the context, say "I cannot find this information in the provided documents."
Be precise with financial figures, dates, and legal terms. Cite sources with filename and page number.

=== CONTEXT ===
{context_block}
=== END CONTEXT ===

Question: {query}

Answer (with citations):"""

    answer = str(llm.complete(prompt)).strip()

    # 7. Format output
    sources, scores = [], []
    for doc, score in cleaned:
        m = doc.metadata
        sources.append({
            "filename": m.get("filename", "?"), "page_number": m.get("page_number", "?"),
            "doc_type": m.get("doc_type", "unknown"), "section_title": m.get("section_title", ""),
            "score": round(float(score), 4),
            "preview": " ".join(doc.text.split()[:25]) + "..."
        })
        scores.append(float(score))

    return {
        "answer": answer, "sources": sources,
        "num_chunks_used": len(sources),
        "confidence": round(np.mean(scores), 4) if scores else 0.0,
        "debug": debug
    }

print("✅ ask_v3 (full pipeline) ready.")

# ── Test Full Pipeline ──
test_questions = [
    "What is the interest rate on the mortgage?",
    "What happens if the borrower defaults?",
    "Is there a prepayment penalty?",
    "What is the monthly payment according to the Closing Disclosure?",
    "What are the escrow requirements?",
]

for q in test_questions:
    print(f"\n{'='*70}")
    print(f"❓ {q}")
    print(f"{'='*70}")
    result = ask_v3(q, verbose=True)
    print(f"\n💬 {result['answer']}")
    print(f"📊 Confidence: {result['confidence']} | Chunks: {result['num_chunks_used']}")
    for s in result['sources']:
        print(f"   📄 {s['filename']} p.{s['page_number']} ({s['doc_type']}) — {s['score']}")

"""---
# ═══════════════════════════════════════════════════════
# PHASE 6 — EVALUATION
# ═══════════════════════════════════════════════════════

## Steps 13-14: RAGAS + Manual Evaluation
"""

eval_questions = [
    {"question": "What is the interest rate on the mortgage?",
     "ground_truth": "The interest rate should be stated in the promissory note or loan agreement."},
    {"question": "What happens if the borrower defaults?",
     "ground_truth": "Default provisions include late fees, acceleration of balance, and potential foreclosure."},
    {"question": "Is there a prepayment penalty?",
     "ground_truth": "The loan documents should specify whether a prepayment penalty exists."},
    {"question": "What is the borrower's monthly payment amount?",
     "ground_truth": "Monthly payment should be in the Closing Disclosure or promissory note."},
    {"question": "What are the escrow requirements?",
     "ground_truth": "Escrow typically covers property taxes and homeowner's insurance."},
    {"question": "What is the loan term?",
     "ground_truth": "The loan term should be stated in the promissory note."},
    {"question": "Who is the lender?",
     "ground_truth": "The lender's name should be on the first page of the mortgage agreement."},
    {"question": "What are the closing costs?",
     "ground_truth": "Closing costs should be itemized in the Closing Disclosure."},
]

# Run pipeline
eval_results = []
print("Running evaluation...\n")
for i, eq in enumerate(eval_questions):
    print(f"  [{i+1}/{len(eval_questions)}] {eq['question']}")
    result = ask_v3(query=eq["question"], verbose=False)
    eval_results.append({
        "question": eq["question"], "ground_truth": eq["ground_truth"],
        "answer": result["answer"],
        "contexts": [s["preview"] for s in result["sources"]],
        "confidence": result["confidence"], "num_chunks": result["num_chunks_used"]
    })
print(f"\n✅ {len(eval_results)} queries evaluated.")

# ─── RAGAS (automated, may need API key for eval LLM) ───
try:
    from ragas import evaluate
    from ragas.metrics import context_precision, context_recall, faithfulness, answer_relevancy
    from datasets import Dataset

    ragas_data = {
        "question": [r["question"] for r in eval_results],
        "answer": [r["answer"] for r in eval_results],
        "contexts": [r["contexts"] for r in eval_results],
        "ground_truth": [r["ground_truth"] for r in eval_results],
    }
    print("📊 Running RAGAS...")
    ragas_results = evaluate(Dataset.from_dict(ragas_data),
                             metrics=[context_precision, context_recall, faithfulness, answer_relevancy])
    print("\n" + "="*50)
    print("📊 RAGAS RESULTS")
    print("="*50)
    for metric, score in ragas_results.items():
        print(f"  {metric}: {score:.4f}")
except Exception as e:
    print(f"⚠️ RAGAS skipped ({e}). Using manual evaluation below.")

# ─── Manual Evaluation (always works) ───
refusal_phrases = ["cannot find", "not in the context", "not in the provided", "no relevant", "unable to find"]

print("\n" + "="*70)
print("📊 MANUAL EVALUATION")
print("="*70)

answered = 0
for r in eval_results:
    is_refusal = any(p in r["answer"].lower() for p in refusal_phrases)
    if not is_refusal: answered += 1
    status = "✅" if not is_refusal else "❌"
    print(f"\n  {status} Conf:{r['confidence']:.2f} Chunks:{r['num_chunks']}")
    print(f"  Q: {r['question']}")
    print(f"  A: {r['answer'][:200]}...")

n = len(eval_results)
avg_conf = np.mean([r["confidence"] for r in eval_results])
avg_chunks = np.mean([r["num_chunks"] for r in eval_results])

print(f"\n{'─'*70}")
print(f"  Answer Rate:     {answered}/{n} ({100*answered/n:.0f}%)")
print(f"  Avg Confidence:  {avg_conf:.4f}")
print(f"  Avg Chunks Used: {avg_chunks:.1f}")
print(f"{'─'*70}")

# ─── Pipeline Comparison: Phase 1 vs Phase 3+4 ───
print("\n" + "="*70)
print("📊 PHASE 1 vs PHASE 3+4 COMPARISON")
print("="*70)

for q in ["What is the interest rate?", "What happens if the borrower defaults?", "Is there a prepayment penalty?"]:
    print(f"\n❓ {q}")
    r1 = ask(q, index=vector_index_v2)
    r3 = ask_v3(q, verbose=False)
    print(f"  📗 Phase 1:   conf={r1['confidence']:.4f} | {r1['answer'][:120]}...")
    print(f"  📘 Phase 3+4: conf={r3['confidence']:.4f} | {r3['answer'][:120]}...")

"""---
# ═══════════════════════════════════════════════════════
# PHASE 5 — GRADIO UI (Launched Last)
# ═══════════════════════════════════════════════════════

`demo.launch()` blocks further cell execution, so the UI is the final step.
Evaluation runs first above so it completes during 'Run All'.

## Step 12: Professional Gradio Interface
"""

import gradio as gr

# ─── Global state for UI ───
CURRENT_INDEX = vector_index_v2
CURRENT_PAGES = all_pages

def process_uploaded_files(file_objs, progress=gr.Progress()):
    """Process uploaded PDFs through full Phase 1+2 pipeline."""
    global CURRENT_INDEX, CURRENT_PAGES, bm25_index, llamaindex_bm25, USE_LLAMAINDEX_BM25
    if not file_objs: return "❌ No files uploaded."

    try:
        progress(0.1, desc="Extracting text...")
        new_pages = []
        for f in file_objs:
            new_pages.extend(ingest_pdf(f.name))
        if not new_pages: return "❌ No text extracted."

        progress(0.3, desc="Classifying pages...")
        new_pages = classify_all_pages(new_pages, llm, use_llm=True)

        progress(0.6, desc="Smart chunking...")
        new_docs = build_phase2_documents(new_pages)

        progress(0.8, desc="Building index...")
        Settings.text_splitter = SentenceSplitter(chunk_size=2048, chunk_overlap=0)
        CURRENT_INDEX = VectorStoreIndex.from_documents(new_docs)
        CURRENT_PAGES = new_pages

        # Always rebuild manual BM25 fallback
        bm25_index = BM25Index(new_docs)

        # Try LlamaIndex BM25 as preferred option
        try:
            from llama_index.retrievers.bm25 import BM25Retriever
            llamaindex_bm25 = BM25Retriever.from_defaults(
                docstore=CURRENT_INDEX.docstore, similarity_top_k=10)
            USE_LLAMAINDEX_BM25 = True
        except:
            USE_LLAMAINDEX_BM25 = False

        progress(1.0, desc="Done!")
        type_counts = Counter(p["doc_type"] for p in new_pages)
        return (
            f"✅ {len(file_objs)} file(s) processed\n"
            f"📄 {len(new_pages)} pages | 📦 {len(new_docs)} chunks\n"
            f"🏷️ Types: {', '.join(f'{t}:{c}' for t,c in type_counts.most_common())}"
        )
    except Exception as e:
        return f"❌ Error: {str(e)}"


def chat_fn(message, history):
    """Chat function: full ask_v3 pipeline → answer + citations."""
    global CURRENT_INDEX
    if CURRENT_INDEX is None:
        yield "⚠️ Please upload and process a document first."
        return
    try:
        result = ask_v3(query=message, vector_idx=CURRENT_INDEX, verbose=False)
        answer = result["answer"]
        citations = "\n\n---\n**🔍 Citations & Confidence:**\n"
        for s in result["sources"]:
            citations += (
                f"• **{s['filename']}** — Page {s['page_number']} "
                f"({s['doc_type']}) [{s.get('section_title','')}]\n"
                f"  Confidence: {s['score']:.2f} | *\"{s['preview']}\"*\n"
            )
        citations += f"\n📦 Chunks: {result['num_chunks_used']} | 📊 Avg conf: {result['confidence']:.2f}"
        yield answer + citations
    except Exception as e:
        yield f"❌ Error: {str(e)}"


print("✅ UI functions ready.")

with gr.Blocks(theme=gr.themes.Soft(), title="Mortgage RAG Analyst") as demo:
    gr.Markdown("# 🏠 Mortgage Document RAG Analyst")
    gr.Markdown(
        "Upload mortgage PDFs. Uses **Hybrid Retrieval (Vector + BM25 + RRF)**, "
        "**Query Rewriting**, **Cross-Encoder Reranking**, and **Context Cleanup**."
    )

    with gr.Row():
        with gr.Column(scale=1, variant="panel"):
            gr.Markdown("### 📂 Document Ingestion")
            file_upload = gr.File(label="Upload PDF(s)", file_types=[".pdf"], file_count="multiple")
            process_btn = gr.Button("⚙️ Process & Index", variant="primary")
            status_output = gr.Textbox(label="Status", interactive=False, lines=4)

            gr.Markdown("### ⚙️ Architecture")
            with gr.Accordion("See Details", open=False):
                gr.Markdown(
                    "- **OCR:** PyMuPDF → PaddleOCR → Tesseract\n"
                    "- **Chunking:** Recursive/hierarchical + semantic merge\n"
                    "- **Retrieval:** Vector (BGE) + BM25 → RRF + query rewriting\n"
                    "- **Reranking:** cross-encoder/ms-marco-MiniLM\n"
                    "- **LLM:** Mistral-7B-Instruct (Q4, GPU)\n"
                    "- **Metadata:** LLM page classification, section titles, table detection"
                )

        with gr.Column(scale=3):
            chatbot = gr.ChatInterface(
                fn=chat_fn,
                examples=[
                    "What is the interest rate?",
                    "What happens if the borrower defaults?",
                    "Is there a prepayment penalty?",
                    "What is the monthly payment?",
                    "What are the escrow requirements?",
                    "Summarize key borrower obligations.",
                    "Compare the interest rate and the APR.",
                ],
                title="💬 Mortgage Document Chat"
            )

    process_btn.click(process_uploaded_files, inputs=[file_upload], outputs=[status_output])

print("✅ UI built.")

demo.launch(share=True, debug=False)

"""---
## 📊 Complete Architecture Summary (For Slides)

| Phase | Step | Component | Implementation |
|-------|------|-----------|---------------|
| **1** | 1 | OCR | PyMuPDF → PaddleOCR (forms/tables) → Tesseract fallback |
| **1** | 1 | Preprocessing | Grayscale, rescale 1.5x, adaptive threshold, bilateral denoise |
| **1** | 2 | Chunking | SentenceSplitter (512 tokens, 50 overlap) |
| **1** | 3 | Embeddings | BAAI/bge-small-en-v1.5 |
| **1** | 3 | Index | LlamaIndex VectorStoreIndex |
| **1** | 4 | LLM | Mistral-7B-Instruct (Q4 GGUF, GPU) |
| **2** | 5 | Smart Chunking | Recursive (section headers) + semantic merge |
| **2** | 6 | Metadata | doc_type, section_title, page_number, table_present |
| **2** | 7 | Classification | Keyword heuristic + LLM fallback |
| **3** | 8 | Retrieval | Hybrid: Vector + BM25 → Reciprocal Rank Fusion |
| **3** | 9 | Query Processing | LLM rewriting + decomposition |
| **4** | 10 | Reranking | cross-encoder/ms-marco-MiniLM-L-6-v2 |
| **4** | 11 | Context Cleanup | Score filter + dedup + token budget |
| **5** | 12 | UI | Gradio Blocks — upload, chat, sources, confidence |
| **6** | 13-14 | Evaluation | RAGAS + manual test suite + pipeline comparison |

### ✅ Complete pipeline ready for demo and presentation.
"""